namespace Surprise_Cash_Verification.Mapper.DTO
{
    public class SurpriseCashAnnexure2DTO
    {
        public string? NameOfInspectingOfficer { get; set; }
        public string? NameOfBranch { get; set; }
        public string? DateOfPrevSurpriseVerification { get; set; }
        public string? OpeningClosingOfBusiness { get; set; }
        public string? OpeningClosingOfBusinessAmount { get; set; }
        public string? SafeCustodyReceiptDated { get; set; }
        public string? SafeCustodyReceipt { get; set; }
        public string? StampedAgreementForms { get; set; }
        public string? StampedAgreementFormsAmount { get; set; }
        public string? NoOfPostParcelsHeldByBranch { get; set; }
        public string? PostParcelsHeldByBranch { get; set; }
        public string? PostalStamps { get; set; }
        public string? PostalStampsAmount { get; set; }
        public string? MonthlyCashVerification { get; set; }
        public string? PeriodicalSurpriseCheck { get; set; }
        public string? KeptUnderJointCustody { get; set; }
        public string? JointCustodianVerifying { get; set; }
        public string? OtherGuidelinesCompiled { get; set; }
        public string? KeyRegisterKeptUnderJointCustody { get; set; }
        public string? KeyRegisterWhetherKeyRegisterMaintained { get; set; }
        public string? KeyRegisterDuplicateSetOfCashKeys { get; set; }
        public string? KeyRegisterDuplicateSetOfCashKeysDate { get; set; }
        public string? KeyRegisterMasterKeyOfTheLockers { get; set; }
        public string? SafetySecurityFoundThatStoringRoomDoorOfBranch { get; set; }
        public string? SafetySecurityFoundThatDoorOfNetworkRoom { get; set; }
        public string? SafetySecurityFoundThatBurglaryAlarmSystem { get; set; }
        public string? WhetherUltravioletLampProvided { get; set; }
        public string? WhetherUltravioletLampWorking { get; set; }
        public string? CCTVSystemIsProvided { get; set; }
        public string? CCTVSystemIsWorking { get; set; }
        public string? CCTVRecordingOfLast90DaysAvailable { get; set; }
        public string? CashCountingMachineProvided { get; set; }
        public string? CashCountingMachineWorking { get; set; }
        public string? NoteSortingMachineProvided { get; set; }
        public string? NoteSortingMachineWorking { get; set; }
        public string? SecurityGuardIsInvolved { get; set; }
        public string? SecurityGuardIsInvolvedDetails { get; set; }
        public string? WhetherBranchHasConductedSurpriseCash { get; set; }
        public string? PhysicalCashInAtmVerified { get; set; }
        public string? Discrepancies { get; set; }
        public string? CreatedBy { get; set; }
        public string? ModifiedBy { get; set; }
        public int? Notes2000 { get; set; }
        public int? Notes500 { get; set; }
        public int? Notes200 { get; set; }
        public int? Notes100 { get; set; }
        public int? Notes50 { get; set; }
        public int? Notes20 { get; set; }
        public int? Notes10 { get; set; }
        public int? Notes5 { get; set; }
        public int? Notes2 { get; set; }
        public int? Notes1 { get; set; }
        public int? Coins10 { get; set; }
        public int? Coins5 { get; set; }
        public int? Coins2 { get; set; }
        public int? Coins1 { get; set; }
        public int? Coins50Paisa { get; set; }
        public string? SafeCustodyReceiptName { get; set; }
        public string? SoiledNotesAmt { get; set; }
        public string? SVBranchCode { get; set; }
        public string? AnnexureComment { get; set; }
        public string? AnnexureStatus { get; set; }
        public string? RegionCode { get; set; }
        public string? ZoneCode { get; set; }
        public string? FinancialYear { get; set; }
        public string? Quater { get; set; }
        public string? KeyRegisterKeptUnderJointCustodyNo { get; set; }
        public string? KeyRegisterWhetherKeyRegisterMaintainedNo { get; set; }
        public string? KeyRegisterDuplicateSetOfCashKeysNo { get; set; }
        public string? KeyRegisterMasterKeyOfTheLockersNo { get; set; }
        public string? SafetySecurityFoundThatBurglaryAlarmSystemNo { get; set; }
        public string? WhetherUltravioletLampProvidedNo { get; set; }
        public string? WhetherUltravioletLampWorkingNo { get; set; }
        public string? CCTVSystemIsProvidedNo { get; set; }
        public string? CCTVSystemIsWorkingNo { get; set; }
        public string? CCTVRecordingOfLast90DaysAvailableNo { get; set; }
        public string? CashCountingMachineProvidedNo { get; set; }
        public string? CashCountingMachineWorkingNo { get; set; }
        public string? WhetherBranchHasConductedSurpriseCashDate { get; set; }
        public string? WhetherBranchHasConductedSurpriseCashNo { get; set; }
        public string? PhysicalCashInAtmVerifiedDate { get; set; }
        public string? PhysicalCashInAtmVerifiedNo { get; set; }
        public string? ZoneName { get; set; }
        public string? RegionName { get; set; }
        public int? Coins20 { get; set; }
        public string? IPAddress { get; set; }
        public string? WhetherMachineSortedNotes { get; set; }
        public string? WhetherMachineSortedNotesNo { get; set; }
        public string? WhetherAvaitabitityofNAM { get; set; }
        public string? WhetherAvaitabitityofNAMNo { get; set; }
        public string? WhetherFIR { get; set; }
        public string? WhetherFIRNo { get; set; }
        public string? MonthlyConsotidatedReport { get; set; }
        public string? MonthlyConsotidatedReportNo { get; set; }
        public string? cashSelectionType { get; set; } //BOD  OR EOD
    }
}
