using Surprise_Cash_Verification.Core.Tables;
using Surprise_Cash_Verification.Mapper.DTO;

namespace Surprise_Cash_Verification.Mapper
{
    public class AutoMapperProfile : AutoMapper.Profile
    {
        public AutoMapperProfile()
        {
            CreateMap<BranchUserAccessDTO, BRANCH_USER_ACCESS>()
                .ForMember(dest => dest.BRANCH_CODE, opt => opt.MapFrom(src => src.BranchCode))
                .ForMember(dest => dest.RO_CODE, opt => opt.MapFrom(src => src.RoCode))
                .ForMember(dest => dest.BRANCH_USERID, opt => opt.MapFrom(src => src.BranchUserId))
                .ForMember(dest => dest.RO_USERID, opt => opt.MapFrom(src => src.RoUserId))
                .ForMember(dest => dest.STATUS, opt => opt.MapFrom(src => src.Status))
                .ForMember(dest => dest.CREATED_BY, opt => opt.MapFrom(src => src.CreatedBy));

            CreateMap<CashDenominationDTO, CASH_DENOMINATION>()
                .ForMember(dest => dest.BRANCH_NAME, opt => opt.MapFrom(src => src.BranchName))
                .ForMember(dest => dest.REGION_NAME, opt => opt.MapFrom(src => src.RegionName))
                .ForMember(dest => dest.NAME_OF_OFFICIER_NOMINATION, opt => opt.MapFrom(src => src.NameOfOfficierNominated))
                .ForMember(dest => dest.SINGLE_LOCK_NOTE_2000, opt => opt.MapFrom(src => src.SingleLockNote2000))
                .ForMember(dest => dest.SINGLE_LOCK_NOTE_500, opt => opt.MapFrom(src => src.SingleLockNote500))
                .ForMember(dest => dest.SINGLE_LOCK_NOTE_200, opt => opt.MapFrom(src => src.SingleLockNote200))
                .ForMember(dest => dest.SINGLE_LOCK_NOTE_50, opt => opt.MapFrom(src => src.SingleLockNote50))
                .ForMember(dest => dest.SINGLE_LOCK_NOTE_20, opt => opt.MapFrom(src => src.SingleLockNote20))
                .ForMember(dest => dest.SINGLE_LOCK_NOTE_10, opt => opt.MapFrom(src => src.SingleLockNote10))
                .ForMember(dest => dest.SINGLE_LOCK_NOTE_5, opt => opt.MapFrom(src => src.SingleLockNote5))
                .ForMember(dest => dest.SINGLE_LOCK_NOTE_2, opt => opt.MapFrom(src => src.SingleLockNote2))
                .ForMember(dest => dest.SINGLE_LOCK_NOTE_1, opt => opt.MapFrom(src => src.SingleLockNote1))
                .ForMember(dest => dest.SINGLE_LOCK_COIN_10, opt => opt.MapFrom(src => src.SingleLockCoin10))
                .ForMember(dest => dest.SINGLE_LOCK_COIN_5, opt => opt.MapFrom(src => src.SingleLockCoin5))
                .ForMember(dest => dest.SINGLE_LOCK_COIN_2, opt => opt.MapFrom(src => src.SingleLockCoin2))
                .ForMember(dest => dest.SINGLE_LOCK_COIN_1, opt => opt.MapFrom(src => src.SingleLockCoin1))
                .ForMember(dest => dest.SINGLE_LOCK_COIN_50P, opt => opt.MapFrom(src => src.SingleLockCoin50P))
                .ForMember(dest => dest.SINGLE_LOCK_GRAND_TOTAL, opt => opt.MapFrom(src => src.SingleLockGrandTotal))
                .ForMember(dest => dest.DOUBLE_LOCK_NOTE_2000, opt => opt.MapFrom(src => src.DoubleLockNote2000))
                .ForMember(dest => dest.DOUBLE_LOCK_NOTE_500, opt => opt.MapFrom(src => src.DoubleLockNote500))
                .ForMember(dest => dest.DOUBLE_LOCK_NOTE_200, opt => opt.MapFrom(src => src.DoubleLockNote200))
                .ForMember(dest => dest.DOUBLE_LOCK_NOTE_50, opt => opt.MapFrom(src => src.DoubleLockNote50))
                .ForMember(dest => dest.DOUBLE_LOCK_NOTE_20, opt => opt.MapFrom(src => src.DoubleLockNote20))
                .ForMember(dest => dest.DOUBLE_LOCK_NOTE_10, opt => opt.MapFrom(src => src.DoubleLockNote10))
                .ForMember(dest => dest.DOUBLE_LOCK_NOTE_5, opt => opt.MapFrom(src => src.DoubleLockNote5))
                .ForMember(dest => dest.DOUBLE_LOCK_NOTE_2, opt => opt.MapFrom(src => src.DoubleLockNote2))
                .ForMember(dest => dest.DOUBLE_LOCK_NOTE_1, opt => opt.MapFrom(src => src.DoubleLockNote1))
                .ForMember(dest => dest.DOUBLE_LOCK_COIN_10, opt => opt.MapFrom(src => src.DoubleLockCoin10))
                .ForMember(dest => dest.DOUBLE_LOCK_COIN_5, opt => opt.MapFrom(src => src.DoubleLockCoin5))
                .ForMember(dest => dest.DOUBLE_LOCK_COIN_2, opt => opt.MapFrom(src => src.DoubleLockCoin2))
                .ForMember(dest => dest.DOUBLE_LOCK_COIN_1, opt => opt.MapFrom(src => src.DoubleLockCoin1))
                .ForMember(dest => dest.DOUBLE_LOCK_COIN_50P, opt => opt.MapFrom(src => src.DoubleLockCoin50P))
                .ForMember(dest => dest.DOUBLE_LOCK_GRAND_TOTAL, opt => opt.MapFrom(src => src.DoubleLockGrandTotal))
                .ForMember(dest => dest.CREATED_BY, opt => opt.MapFrom(src => src.CreatedBy));

            CreateMap<StatusOfReportByDyrhDTO, STATUS_OF_REPORT_BY_DYRH>()
                .ForMember(dest => dest.BRANCH_NAME, opt => opt.MapFrom(src => src.BranchName))
                .ForMember(dest => dest.REGION_NAME, opt => opt.MapFrom(src => src.RegionName))
                .ForMember(dest => dest.NAME_OF_OFFICIER_NOMINATED, opt => opt.MapFrom(src => src.NameOfOfficierNominated))
                .ForMember(dest => dest.STATUS, opt => opt.MapFrom(src => src.Status))
                .ForMember(dest => dest.CREATED_BY, opt => opt.MapFrom(src => src.CreatedBy));

            CreateMap<SurpriseCashAnnexure1DTO, SURPRISE_CASH_ANNEXURE_1>()
                .ForMember(dest => dest.FROM_REGION_NAME, opt => opt.MapFrom(src => src.FromRegionName))
                .ForMember(dest => dest.FROM_DYRH_NAME, opt => opt.MapFrom(src => src.FromDyrhName))
                .ForMember(dest => dest.TO_BRANCH_OFFICER_NAME, opt => opt.MapFrom(src => src.officers.FirstOrDefault().ToBranchOfficierName))
                .ForMember(dest => dest.TO_BRANCH_OFFICER_BRANCH_NAME, opt => opt.MapFrom(src => src.officers.FirstOrDefault().ToBranchOfficierBranchName))
                .ForMember(dest => dest.TO_BRANCH_OFFICER_DESIGNATION, opt => opt.MapFrom(src => src.officers.FirstOrDefault().ToBranchOfficierDesignation))
                .ForMember(dest => dest.APPLICATION_DATE, opt => opt.MapFrom(src => src.officers.FirstOrDefault().ApplicationDate))
                .ForMember(dest => dest.CREATED_BY, opt => opt.MapFrom(src => src.CreatedBy))
                .ForMember(dest => dest.IC_NO, opt => opt.MapFrom(src => src.officers.FirstOrDefault().ICNO))
                .ForMember(dest => dest.IC_NO_DATE, opt => opt.MapFrom(src => src.officers.FirstOrDefault().ICNODate))
                .ForMember(dest => dest.IO_BRANCH_CODE, opt => opt.MapFrom(src => src.newBranches.FirstOrDefault().IoBranchCode))
                .ForMember(dest => dest.SV_BRANCH_CODE, opt => opt.MapFrom(src => src.newBranches.FirstOrDefault().SvBranchCode))
                .ForMember(dest => dest.FINANCIAL_YEAR, opt => opt.MapFrom(src => src.FinancialYear))
                .ForMember(dest => dest.QUATER, opt => opt.MapFrom(src => src.Quater));
                

            CreateMap<SurpriseCashAnnexure2DTO, SURPRISE_CASH_ANNEXURE_2>()
                .ForMember(dest => dest.NAME_OF_INSPECTING_OFFICER, opt => opt.MapFrom(src => src.NameOfInspectingOfficer))
                .ForMember(dest => dest.NAME_OF_BRANCH, opt => opt.MapFrom(src => src.NameOfBranch))
                .ForMember(dest => dest.DATE_OF_PREV_SURPRISE_VERIFICATION, opt => opt.MapFrom(src => src.DateOfPrevSurpriseVerification))
                .ForMember(dest => dest.OPENING_CLOSING_OF_BUSINESS, opt => opt.MapFrom(src => src.OpeningClosingOfBusiness))
                .ForMember(dest => dest.OPENING_CLOSING_OF_BUSINESS_AMOUNT, opt => opt.MapFrom(src => src.OpeningClosingOfBusinessAmount))
                .ForMember(dest => dest.SAFE_CUSTODY_RECEIPT_DATED, opt => opt.MapFrom(src => src.SafeCustodyReceiptDated))
                .ForMember(dest => dest.SAFE_CUSTODY_RECEIPT, opt => opt.MapFrom(src => src.SafeCustodyReceipt))
                .ForMember(dest => dest.STAMPED_AGREEMENT_FORMS, opt => opt.MapFrom(src => src.StampedAgreementForms))
                .ForMember(dest => dest.STAMPED_AGREEMENT_FORMS_AMOUNT, opt => opt.MapFrom(src => src.StampedAgreementFormsAmount))
                .ForMember(dest => dest.NO_OF_POST_PARCELS_HELD_BY_BRANCH, opt => opt.MapFrom(src => src.NoOfPostParcelsHeldByBranch))
                .ForMember(dest => dest.POST_PARCELS_HELD_BY_BRANCH, opt => opt.MapFrom(src => src.PostParcelsHeldByBranch))
                .ForMember(dest => dest.POSTAL_STAMPS, opt => opt.MapFrom(src => src.PostalStamps))
                .ForMember(dest => dest.POSTAL_STAMPS_AMOUNT, opt => opt.MapFrom(src => src.PostalStampsAmount))
                .ForMember(dest => dest.MONTHLY_CASH_VERIFICATION_OF_CASH, opt => opt.MapFrom(src => src.MonthlyCashVerification))
                .ForMember(dest => dest.PERIODICAL_SURPRISE_CHECK, opt => opt.MapFrom(src => src.PeriodicalSurpriseCheck))
                .ForMember(dest => dest.KEPT_UNDER_JOINT_CUSTODY, opt => opt.MapFrom(src => src.KeptUnderJointCustody))
                .ForMember(dest => dest.JOINT_CUSTODIAN_VERIFYING, opt => opt.MapFrom(src => src.JointCustodianVerifying))
                .ForMember(dest => dest.OTHER_GUIDELINES_COMPILED, opt => opt.MapFrom(src => src.OtherGuidelinesCompiled))
                .ForMember(dest => dest.KEY_REGISTER_KEPT_UNDER_JOINT_CUSTODY, opt => opt.MapFrom(src => src.KeyRegisterKeptUnderJointCustody))
                .ForMember(dest => dest.KEY_REGISTER_WHETHER_KEY_REGISTER_MAINTAINED, opt => opt.MapFrom(src => src.KeyRegisterWhetherKeyRegisterMaintained))
                .ForMember(dest => dest.KEY_REGISTER_DUPTICATE_SET_OF_CASH_KEYS, opt => opt.MapFrom(src => src.KeyRegisterDuplicateSetOfCashKeys))
                .ForMember(dest => dest.KEY_REGISTER_DUPTICATE_SET_OF_CASH_KEYS_DATE, opt => opt.MapFrom(src => src.KeyRegisterDuplicateSetOfCashKeysDate))
                .ForMember(dest => dest.KEY_REGISTER_MASTER_KEY_OF_THE_LOCKERS, opt => opt.MapFrom(src => src.KeyRegisterMasterKeyOfTheLockers))
                .ForMember(dest => dest.SAFETY_SECURITY_FOUND_THAT_STRONG_ROOM_DOOR_OF_BRANCH, opt => opt.MapFrom(src => src.SafetySecurityFoundThatStoringRoomDoorOfBranch))
                .ForMember(dest => dest.SAFETY_SECURITY_FOUND_THAT_DOOR_OF_NETWORK_ROOM, opt => opt.MapFrom(src => src.SafetySecurityFoundThatDoorOfNetworkRoom))
                .ForMember(dest => dest.SAFETY_SECURITY_FOUND_THAT_BURGLARY_ALARM_SYSTEM, opt => opt.MapFrom(src => src.SafetySecurityFoundThatBurglaryAlarmSystem))
                .ForMember(dest => dest.WHETHER_ULTRAVIOLET_LAMP_PROVIDED, opt => opt.MapFrom(src => src.WhetherUltravioletLampProvided))
                .ForMember(dest => dest.WHETHER_ULTRAVIOLET_LAMP_WORKING, opt => opt.MapFrom(src => src.WhetherUltravioletLampWorking))
                .ForMember(dest => dest.CCTV_SYSTEM_IS_PROVIDED, opt => opt.MapFrom(src => src.CCTVSystemIsProvided))
                .ForMember(dest => dest.CCTV_SYSTEM_IS_WORKING, opt => opt.MapFrom(src => src.CCTVSystemIsWorking))
                .ForMember(dest => dest.CCTV_RECORDING_OF_LAST_90DAYS_AVAILABLE, opt => opt.MapFrom(src => src.CCTVRecordingOfLast90DaysAvailable))
                .ForMember(dest => dest.CASH_COUNTING_MACHINE_PROVIDED, opt => opt.MapFrom(src => src.CashCountingMachineProvided))
                .ForMember(dest => dest.CASH_COUNTING_MACHINE_WORKING, opt => opt.MapFrom(src => src.CashCountingMachineWorking))
                .ForMember(dest => dest.NOTE_SORTING_MACHINE_PROVIDED, opt => opt.MapFrom(src => src.NoteSortingMachineProvided))
                .ForMember(dest => dest.NOTE_SORTING_MACHINE_WORKING, opt => opt.MapFrom(src => src.NoteSortingMachineWorking))
                .ForMember(dest => dest.SECURITY_GUARD_IS_INVOLVED, opt => opt.MapFrom(src => src.SecurityGuardIsInvolved))
                .ForMember(dest => dest.SECURITY_GUARD_IS_INVOLVED_DETAILS, opt => opt.MapFrom(src => src.SecurityGuardIsInvolvedDetails))
                .ForMember(dest => dest.WHETHER_BRANCH_HAS_CONDUCTED_SURPRISE_CASH, opt => opt.MapFrom(src => src.WhetherBranchHasConductedSurpriseCash))
                .ForMember(dest => dest.PHYSICAL_CASH_IN_ATM_VERIFIED, opt => opt.MapFrom(src => src.PhysicalCashInAtmVerified))
                .ForMember(dest => dest.DISCREPANCIES, opt => opt.MapFrom(src => src.Discrepancies))
                .ForMember(dest => dest.CREATED_BY, opt => opt.MapFrom(src => src.CreatedBy))
                .ForMember(dest => dest.NOTES_2000, opt => opt.MapFrom(src => src.Notes2000))
                .ForMember(dest => dest.NOTES_500, opt => opt.MapFrom(src => src.Notes500))
                .ForMember(dest => dest.NOTES_200, opt => opt.MapFrom(src => src.Notes200))
                .ForMember(dest => dest.NOTES_100, opt => opt.MapFrom(src => src.Notes100))
                .ForMember(dest => dest.NOTES_50, opt => opt.MapFrom(src => src.Notes50))
                .ForMember(dest => dest.NOTES_20, opt => opt.MapFrom(src => src.Notes20))
                .ForMember(dest => dest.NOTES_10, opt => opt.MapFrom(src => src.Notes10))
                .ForMember(dest => dest.NOTES_5, opt => opt.MapFrom(src => src.Notes5))
                .ForMember(dest => dest.NOTES_2, opt => opt.MapFrom(src => src.Notes2))
                .ForMember(dest => dest.NOTES_1, opt => opt.MapFrom(src => src.Notes1))
                .ForMember(dest => dest.COINS_10, opt => opt.MapFrom(src => src.Coins10))
                .ForMember(dest => dest.COINS_5, opt => opt.MapFrom(src => src.Coins5))
                .ForMember(dest => dest.COINS_2, opt => opt.MapFrom(src => src.Coins2))
                .ForMember(dest => dest.COINS_1, opt => opt.MapFrom(src => src.Coins1))
                .ForMember(dest => dest.COINS_50_PAISA, opt => opt.MapFrom(src => src.Coins50Paisa))
                .ForMember(dest => dest.SAFE_CUSTODY_RECEIPTNAME, opt => opt.MapFrom(src => src.SafeCustodyReceiptName))
                .ForMember(dest => dest.SOILED_NOTES_AMT, opt => opt.MapFrom(src => src.SoiledNotesAmt))
                .ForMember(dest => dest.SV_BRANCH_CODE, opt => opt.MapFrom(src => src.SVBranchCode))
                .ForMember(dest => dest.ANNEXURE_STATUS, opt => opt.MapFrom(src => src.AnnexureStatus))
                .ForMember(dest => dest.ANNEXURE_COMMENT, opt => opt.MapFrom(src => src.AnnexureComment))
                .ForMember(dest => dest.REGION_CODE, opt => opt.MapFrom(src => src.RegionCode))
                .ForMember(dest => dest.ZONE_CODE, opt => opt.MapFrom(src => src.ZoneCode))
                .ForMember(dest => dest.FINANCIAL_YEAR, opt => opt.MapFrom(src => src.FinancialYear))
                .ForMember(dest => dest.QUATER, opt => opt.MapFrom(src => src.Quater))
                .ForMember(dest => dest.KEY_REGISTER_KEPT_UNDER_JOINT_CUSTODY_NO, opt => opt.MapFrom(src => src.KeyRegisterKeptUnderJointCustodyNo))
                .ForMember(dest => dest.KEY_REGISTER_WHETHER_KEY_REGISTER_MAINTAINED_NO, opt => opt.MapFrom(src => src.KeyRegisterWhetherKeyRegisterMaintainedNo))
                .ForMember(dest => dest.KEY_REGISTER_DUPTICATE_SET_OF_CASH_KEYS_NO, opt => opt.MapFrom(src => src.KeyRegisterDuplicateSetOfCashKeysNo))
                .ForMember(dest => dest.KEY_REGISTER_MASTER_KEY_OF_THE_LOCKERS_NO, opt => opt.MapFrom(src => src.KeyRegisterMasterKeyOfTheLockersNo))
                .ForMember(dest => dest.SAFETY_SECURITY_FOUND_THAT_BURGLARY_ALARM_SYSTEM_NO, opt => opt.MapFrom(src => src.SafetySecurityFoundThatBurglaryAlarmSystemNo))
                .ForMember(dest => dest.WHETHER_ULTRAVIOLET_LAMP_PROVIDED_NO, opt => opt.MapFrom(src => src.WhetherUltravioletLampProvidedNo))
                .ForMember(dest => dest.WHETHER_ULTRAVIOLET_LAMP_WORKING_NO, opt => opt.MapFrom(src => src.WhetherUltravioletLampWorkingNo))
                .ForMember(dest => dest.CCTV_SYSTEM_IS_PROVIDED_NO, opt => opt.MapFrom(src => src.CCTVSystemIsProvidedNo))
                .ForMember(dest => dest.CCTV_SYSTEM_IS_WORKING_NO, opt => opt.MapFrom(src => src.CCTVSystemIsWorkingNo))
                .ForMember(dest => dest.CCTV_RECORDING_OF_LAST_90DAYS_AVAILABLE_NO, opt => opt.MapFrom(src => src.CCTVRecordingOfLast90DaysAvailableNo))
                .ForMember(dest => dest.CASH_COUNTING_MACHINE_PROVIDED_NO, opt => opt.MapFrom(src => src.CashCountingMachineProvidedNo))
                .ForMember(dest => dest.CASH_COUNTING_MACHINE_WORKING_NO, opt => opt.MapFrom(src => src.CashCountingMachineWorkingNo))
                .ForMember(dest => dest.WHETHER_BRANCH_HAS_CONDUCTED_SURPRISE_CASH_DATE, opt => opt.MapFrom(src => src.WhetherBranchHasConductedSurpriseCashDate))
                .ForMember(dest => dest.WHETHER_BRANCH_HAS_CONDUCTED_SURPRISE_CASH_NO, opt => opt.MapFrom(src => src.WhetherBranchHasConductedSurpriseCashNo))
                .ForMember(dest => dest.PHYSICAL_CASH_IN_ATM_VERIFIED_DATE, opt => opt.MapFrom(src => src.PhysicalCashInAtmVerifiedDate))
                .ForMember(dest => dest.PHYSICAL_CASH_IN_ATM_VERIFIED_NO, opt => opt.MapFrom(src => src.PhysicalCashInAtmVerifiedNo))
                .ForMember(dest => dest.ZONE_NAME, opt => opt.MapFrom(src => src.ZoneName))
                .ForMember(dest => dest.REGION_NAME, opt => opt.MapFrom(src => src.RegionName))
                .ForMember(dest => dest.COINS_20, opt => opt.MapFrom(src => src.Coins20))
                .ForMember(dest => dest.WHETHERMACHINESORTEDNOTES, opt => opt.MapFrom(src => src.WhetherMachineSortedNotes))
                .ForMember(dest => dest.WHETHERMACHINESORTEDNOTESNO, opt => opt.MapFrom(src => src.WhetherMachineSortedNotesNo))
                .ForMember(dest => dest.WHETHERAVAITABITITYOFNAM, opt => opt.MapFrom(src => src.WhetherAvaitabitityofNAM))
                .ForMember(dest => dest.WHETHERAVAITABITITYOFNAMNO, opt => opt.MapFrom(src => src.WhetherAvaitabitityofNAMNo))
                .ForMember(dest => dest.WHETHERFIR, opt => opt.MapFrom(src => src.WhetherFIR))
                .ForMember(dest => dest.WHETHERFIRNO, opt => opt.MapFrom(src => src.WhetherFIRNo))
                .ForMember(dest => dest.MONTHTYCONSOTIDATEDREPORT, opt => opt.MapFrom(src => src.MonthlyConsotidatedReport))
                .ForMember(dest => dest.MONTHTYCONSOTIDATEDREPORTNO, opt => opt.MapFrom(src => src.MonthlyConsotidatedReportNo));


            CreateMap<SurpriseCashAnnexure3DTO, SURPRISE_CASH_ANNEXURE_3>()
                .ForMember(dest => dest.REGIONAL_HEAD, opt => opt.MapFrom(src => src.RegionalHead))
                .ForMember(dest => dest.REGIONAL_OFFICE, opt => opt.MapFrom(src => src.RegionalOffice))
                .ForMember(dest => dest.ZONAL_HEAD, opt => opt.MapFrom(src => src.ZonalHead))
                .ForMember(dest => dest.ZONAL_OFFICE, opt => opt.MapFrom(src => src.ZonalOffice))
                .ForMember(dest => dest.ANNEXURE_3_DATE, opt => opt.MapFrom(src => src.Date))
                .ForMember(dest => dest.DISCREPANCIES, opt => opt.MapFrom(src => src.Discrepancies))
                .ForMember(dest => dest.CREATED_BY, opt => opt.MapFrom(src => src.CreatedBy))
                .ForMember(dest => dest.REGION_CODE, opt => opt.MapFrom(src => src.RegionCode))
                .ForMember(dest => dest.ZONE_CODE, opt => opt.MapFrom(src => src.ZoneCode))
                .ForMember(dest => dest.FINANCIAL_YEAR, opt => opt.MapFrom(src => src.FinancialYearAnnexure3))
                .ForMember(dest => dest.QUATER, opt => opt.MapFrom(src => src.QuaterAnnexure3))
                .ForMember(dest => dest.ANNEXURE_STATUS, opt => opt.MapFrom(src => src.AnnexureStatus));


            CreateMap<SurpriseCashAnnexure4DTO, SURPRISE_CASH_ANNEXURE_4>()
                .ForMember(dest => dest.REGIONAL_HEAD, opt => opt.MapFrom(src => src.ZonalHead4))
                .ForMember(dest => dest.REGIONAL_OFFICE, opt => opt.MapFrom(src => src.ZonalOffice4))
                .ForMember(dest => dest.OPERATIONS_DEPARTMENT, opt => opt.MapFrom(src => src.OperationDepartment4))
                .ForMember(dest => dest.CENTRAT_OFFICE_ANNEX, opt => opt.MapFrom(src => src.CentralOfficeAnnex))
                .ForMember(dest => dest.ANNEXURE_4_DATE, opt => opt.MapFrom(src => src.Date4))
                .ForMember(dest => dest.DISCREPANCIES, opt => opt.MapFrom(src => src.Discrepancies4))
                .ForMember(dest => dest.CREATED_BY, opt => opt.MapFrom(src => src.CREATED_BY))
                .ForMember(dest => dest.ZONE_CODE, opt => opt.MapFrom(src => src.ZoneCode))
                .ForMember(dest => dest.ZONE_NAME, opt => opt.MapFrom(src => src.ZoneName))
                .ForMember(dest => dest.ANNEXURE_STATUS, opt => opt.MapFrom(src => src.AnnexureStatus));

        }
    }
}
